config/routes.rb
Rails.application.routes.draw do
  resources :facilities

  root 'facilities#index'

end

app/models/facility.rb
class Facility < ActiveRecord::Base
	validates :title, presence: true,
	                  length: { minimum: 3 }

	validates :description, presence: true,
	                  length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

		def flash_class(type)
		case type
		when :alert
			"alert-danger"
		when :notice
			"alert-info"
		else
			""
		end
	end
	
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<%= form_for(@facility) do |f| %>
  <% if @facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% @facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-md-1">
      <span id="facilityIcon"><%= image_tag("facilityicon.png", height: 60) %></span>
    </div>
    <div class="col-md-3">
      <h1>Facilities</h1>
    </div>
    <div id="facilityButton" class="col-md-2">
      <%= link_to 'Add New Facility', new_facility_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<% @facilities.each do |facility| %>
  <div class="status">
    <div class="row">
      <div class="col-md-7">
        <strong><%= link_to facility.title, facility %></strong>
      </div>
    </div>
  </div>
  <hr />
<% end %>

app/views/facilities/new.html.erb
<h1>New facility</h1>

<%= render 'form' %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @facility.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @facility.description %>
</p>

<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trakkey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%- favicon_link_tag 'favicon.ico' %>
</head>
<body>

	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<a href="#" class="navbar-brand">TrakKey</a>
			<ul class="nav navbar-nav">
				<li><%= link_to "Facilities", facilities_path %></li>
			</ul>
		</div>

	</div>

	<div class="container">

		<% if flash[:notice] %>
		
			<div class="alert alert-info alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times</button>
				<%= flash[:notice] %>
			</div>
		<% end %>

		<% if flash[:alert] %>
			<div class="alert alert-danger alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times</button>
				<%= flash[:alert] %>
			</div>
		<% end %>

		<%= yield %>

	</div>


</body>
</html>